# Generated by Django 5.1.4 on 2025-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razorpay_order_id',
            new_name='paystack_reference',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='razorpay_payment_id',
            new_name='paystack_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_signature',
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
