# Generated by Django 5.1.4 on 2025-01-14 14:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_cart_coupon_remove_cartitem_color_variant_and_more"),
        ("products", "0015_productreview_dislikes_productreview_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
        migrations.RemoveField(
            model_name="product",
            name="color_variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_variant",
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "product")},
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="size_variant",
        ),
    ]
